import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="NavBar">
          <div className="NavBar__links">
            <a href="/">Home</a>
            <a href="/posts">Posts</a>
            <a href="/albums">Albums</a>
          </div>
        </div>
        {children}
        <div>BottomBar</div>
      </body>
    </html>
  );
}
